// term: lo que se busca; aliases: valores aceptados del campo "brand"; name: regex que debe cumplir el nombre
// (para marcas con nombre genérico); strong: regex que basta por sí sola en el nombre del producto.
export const BRANDS = [
 { id: 1, term: "olipop", aliases: ["olipop"], strong: /\bolipop\b/i },
 { id: 2, term: "bombas", aliases: ["bombas"], name: /calcet|media|sock|meia/i },
 { id: 3, term: "magic spoon", aliases: ["magicspoon"], strong: /magic spoon/i, name: /cereal|granola|barra|bar/i },
 { id: 4, term: "drunk elephant", aliases: ["drunkelephant"], strong: /drunk elephant/i },
 { id: 5, term: "chomps", aliases: ["chomps"], name: /carne|beef|stick|turkey|pavo|jerky/i },
 { id: 6, term: "graza", aliases: ["graza"], name: /aceite|oliva|olive|azeite/i },
 { id: 7, term: "alani nu", aliases: ["alaninu", "alani"], strong: /alani nu/i },
 { id: 8, term: "blueland", aliases: ["blueland"], strong: /\bblueland\b/i },
 { id: 9, term: "liquid iv", aliases: ["liquidiv", "liquidi.v."], strong: /liquid\s*i\.?\s*v\b/i },
 { id: 10, term: "mudwtr", aliases: ["mudwtr"], strong: /mud\s*\\?\s*wtr/i },
 { id: 11, term: "athletic brewing", aliases: ["athleticbrewing", "athleticbrewingcompany", "athletic"], strong: /athletic brewing/i, name: /cerveza|beer|cerveja|run wild|upside|lite/i },
 { id: 12, term: "hims", aliases: ["hims", "himshers", "hims&hers"], name: /shampoo|champ|acondicion|minoxidil|hair|cabello|biotin/i },
 { id: 13, term: "brightland", aliases: ["brightland"], strong: /\bbrightland\b/i },
 { id: 14, term: "cometeer", aliases: ["cometeer"], strong: /\bcometeer\b/i },
 { id: 15, term: "osea", aliases: ["osea", "oseamalibu"], name: /oil|aceite|serum|crema|cream|body|corporal|balm|bálsamo|cleanser|limpiador/i },
 { id: 16, term: "touchland", aliases: ["touchland"], strong: /\btouchland\b/i },
 { id: 17, term: "ghia", aliases: ["ghia"], name: /aperitiv|spritz|sin alcohol|non-alcoholic/i },
 { id: 18, term: "jinx", aliases: ["jinx"], name: /perro|dog|croqueta|alimento|kibble|treat/i },
 { id: 19, term: "oura", aliases: ["oura", "ouraring"], strong: /\boura\b/i },
 { id: 20, term: "caraway", aliases: ["caraway", "carawayhome"], name: /sart[eé]n|olla|cacerola|cookware|pan|bateria|batería/i },
 { id: 21, term: "diaspora co", aliases: ["diasporaco", "diaspora"], name: /especia|spice|c[uú]rcuma|turmeric|masala|chile|pepper|pimienta/i },
 { id: 22, term: "studs", aliases: ["studs"], name: /arete|earring|piercing/i },
 { id: 23, term: "fly by jing", aliases: ["flybyjing"], strong: /fly\s*by\s*jing/i },
 { id: 24, term: "recess", aliases: ["recess"], name: /bebida|agua|sparkling|mood|magnesio|magnesium|calm/i },
 { id: 25, term: "immi", aliases: ["immi", "immieats"], name: /ramen|noodle|fideo/i },
 { id: 26, term: "jolie", aliases: ["jolie", "jolieskinco", "jolieskincompany"], name: /ducha|shower|filtro|filter|regadera/i },
 { id: 27, term: "arrae", aliases: ["arrae"], strong: /\barrae\b/i },
 { id: 28, term: "notco", aliases: ["notco", "thenotcompany", "thenotco", "notcompany"], strong: /\bnot\s?co\b|notmilk|not milk|notmayo|not mayo|notburger|not burger|notchicken|not icecream/i },
 { id: 29, term: "poppi", aliases: ["poppi"], name: /soda|bebida|prebi/i },
 { id: 30, term: "starface", aliases: ["starface", "starfaceworld"], strong: /\bstarface\b/i },
 { id: 31, term: "drybar", aliases: ["drybar"], strong: /\bdrybar\b/i },
 { id: 32, term: "maude", aliases: ["maude"], name: /lubric|shine|massage|masaje|condon|cond[oó]n|vibe/i },
 { id: 33, term: "liquid death", aliases: ["liquiddeath"], strong: /liquid death/i },
 { id: 34, term: "prime hydration", aliases: ["prime", "primehydration"], name: /hidrat|hydrat|bebida|drink|energ/i },
 { id: 35, term: "celsius", aliases: ["celsius"], name: /bebida|energ|drink|sparkling|lata|can/i },
 { id: 36, term: "rhode", aliases: ["rhode", "rhodeskin"], name: /lip|labial|peptide|glaz|blush|rubor|serum|barrier/i },
 { id: 37, term: "glossier", aliases: ["glossier"], strong: /\bglossier\b/i },
 { id: 38, term: "rare beauty", aliases: ["rarebeauty"], strong: /rare beauty/i },
 { id: 39, term: "fenty beauty", aliases: ["fentybeauty", "fenty", "fentyskin"], strong: /fenty/i },
 { id: 40, term: "haus labs", aliases: ["hauslabs", "hauslaboratories"], strong: /haus lab/i },
 { id: 41, term: "jones road", aliases: ["jonesroad", "jonesroadbeauty"], strong: /jones road/i },
 { id: 42, term: "ritual essential", aliases: ["ritual"], name: /vitamin|multivit|essential|prenatal|synbiotic|protein|prote[ií]na/i },
 { id: 43, term: "seed synbiotic", aliases: ["seed", "seedhealth"], name: /synbiotic|probi[oó]tic|ds-01|simbi[oó]tic/i },
 { id: 44, term: "native deodorant", aliases: ["native"], name: /desodorante|deodorant|body wash|jab[oó]n|shampoo|champ/i },
 { id: 45, term: "cuts clothing", aliases: ["cuts", "cutsclothing"], name: /camis|playera|shirt|polo|pant|jogger|hoodie|sudadera/i },
 { id: 46, term: "vuori", aliases: ["vuori"], strong: /\bvuori\b/i },
 { id: 47, term: "gymshark", aliases: ["gymshark"], strong: /gym\s?shark/i },
 { id: 48, term: "allbirds", aliases: ["allbirds"], strong: /\ballbirds\b/i },
 { id: 49, term: "on running", aliases: ["on", "onrunning", "oncloud"], name: /cloud|zapatill|tenis|t[eê]nis|shoe|calzado|running/i },
 { id: 50, term: "hoka", aliases: ["hoka", "hokaoneone"], strong: /\bhoka\b/i },
 { id: 51, term: "yeti", aliases: ["yeti"], name: /rambler|tundra|hielera|cooler|termo|vaso|botella|tumbler|roadie|hopper|taza|mug|copo|garrafa/i },
 { id: 52, term: "stanley", aliases: ["stanley", "stanley1913"], name: /termo|vaso|botella|quencher|tumbler|thermo|jarra|copo|garrafa|taza|mug|lonchera|hielera|cooler|iceflow|aerolight|adventure|classic/i },
 { id: 53, term: "owala", aliases: ["owala"], strong: /\bowala\b/i },
 { id: 54, term: "caulipower", aliases: ["caulipower"], strong: /caulipower/i },
 { id: 55, term: "partake", aliases: ["partake", "partakefoods"], name: /galleta|cookie|cracker|graham|mix|harina|wafer/i },
];
